config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources  :movies
  resources  :actors
  resources  :ratings
  resources  :users
  root :to => "movies#index"

end

app/models/actor.rb
class Actor < ActiveRecord::Base
  has_many :movie_actors, dependent: :destroy
  has_many :movies, through: :movie_actors
  validates :name, presence: true
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :songs, dependent: :destroy
  has_many :movie_actors, dependent: :destroy
  has_many :actors, through: :movie_actors
  has_many :ratings, as: :ratable
  validates :name, presence: true
  accepts_nested_attributes_for :songs, :movie_actors, allow_destroy: true
  accepts_nested_attributes_for :ratings, allow_destroy: true
end

app/models/movie_actor.rb
class MovieActor < ActiveRecord::Base
  belongs_to :movie
  belongs_to :actor
end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :user
  belongs_to :ratable, polymorphic: true
  validates_numericality_of :stars
  validates :stars, inclusion: {in: 0..5}
  validate :user_rate
  def user_rate
    if Rating.where(user_id: self.user_id, ratable_id: self.ratable_id, ratable_type: self.ratable_type).exists?
       errors.add(:user_id," user cannot rate twice")
      end
  end

end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :movie
  has_many :ratings, as: :ratable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :ratings
  validates :name, presence: true
  validates_associated :ratings
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  def index
    @actors = Actor.all
  end
  def show
    @actor= Actor.find(params[:id])
    @movies = @actor.movies
    @rol= @actor.movie_actors
  end
  def new
    @actor = Actor.new
  end

  def create
    #puts params[:actor]
    @actor = Actor.new(actors_params)
    if @actor.save
      redirect_to actors_path
    else
      render action: 'new'
    end
  end

  def actors_params
    #puts params.require(:actor).permit(:name)
    params.require(:actor).permit(:name)
  end
  def edit
    @actor = Actor.find(params[:id])
    
  end
  def update
    @actor = Actor.find(params[:id])
    if @actor.update_attributes(actors_params)
       redirect_to actors_path
    else
       render action: 'edit'
    end 
  end
  def destroy
    @actor = Actor.find(params[:id])
    @actor.destroy
    redirect_to actors_path
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end
  def show
    @movie= Movie.find(params[:id])
    @actor= @movie.actors
  end
  def new
    @movie = Movie.new
    @actors = Actor.all
    @rating = Rating.new
  end

  def create
    #puts params[:actor]
    @movie = Movie.new(movies_params)
    if @movie.save
      redirect_to movies_path
    else
      render action: 'new'
    end
  end

  def movies_params
    #puts params.require(:actor).permit(:name)
    params.require(:movie).permit(:id, :name, songs_attributes: [:id, :name,:composer, :_destroy], movie_actors_attributes: [:id, :actor_id, :role, :_destroy])
  end
  def edit
    @movie = Movie.find(params[:id])
    
  end
  def update
    @movie = Movie.find(params[:id])
    if @movie.update_attributes(movies_params)
       redirect_to movies_path
    else
       render action: 'edit'
    end 
  end
  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    redirect_to movies_path
  end


end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/actors/edit.html.erb
<%= form_for @actor, url:actor_path do |f| %>
      <%= @actor.errors.full_messages unless @actor.errors.empty? %>
Name: <%= f.text_field :name%> </br>
      <%= f.submit "Save" %>
<% end %>

app/views/actors/index.html.erb
  Welcome to my world


  <%#@actors.all.each do |actor| %>
  <%# link_to actor.name, actor_path(actor)%>
  <%#end%>

    <% @actors.all.each do |actor| %>
   <p> <%= link_to actor.name, actor%>.....<%=link_to "Edit", edit_actor_path(actor) %>....<%= link_to "Delete", actor_path(actor), method: :delete%> </p> 
    <% end %> 

<%= link_to "Create A New Actor", new_actor_path %>
<%= link_to "Add An Actor", new_actor_path %> 
<% #link_to "Edit An Actor", edit_actor_path %>
<% #link_to "Destroy An Actor", edit_actor_path %>

app/views/actors/new.html.erb
<%= form_for @actor, url: actors_path do |f| %>
      <%= @actor.errors.full_messages unless @actor.errors.empty? %>
Name: <%= f.text_field :name%> </br>
      <%= f.submit "Save" %>
<% end %>

app/views/actors/show.html.erb
<%=p @actor.name%>
<%@movies.all.each do |a|%>
<%=p a.name%>
<%end%>
<%=@rol.map(&:role)%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Imdb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if user_signed_in? %>
  <%= link_to"Sign Out",destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to"Sign In", new_user_session_path %>
  <%= link_to"Sign Up", new_user_registration_path %>
<% end %>

<%= yield %>

</body>
</html>

app/views/movies/edit.html.erb
<%= simple_nested_form_for @movie do |f| %>
  <%= f. label :Movie_Name %>
  <%= f.text_field :name %>

<h1>SONGS</h1>
<%= f.simple_fields_for :songs do |song| %>
  <%= song. label :Song_Name %>
  <%= song.text_field :name %>
  <%= song. label :Composer_Name %>
  <%= song.text_field :composer %>
  <%= song.link_to_remove "Delete"%>
<% end %>
<%= f.link_to_add "Add new song",:songs %>

<h1>ACTORS</h1>
<%= f.simple_fields_for :movie_actors do |actor1| %>
  <%= actor1.input :actor_id, collection: @actors %>
  <%= actor1.label :Role %>
  <%= actor1.text_field :role%>
  <%= actor1.link_to_remove "Delete"%>
<% end %>
<%= f.link_to_add "Add new Actor",:movie_actors %>

  <br><%= f.button :submit %></br>
<% end %>

app/views/movies/index.html.erb
<html>
<body bgcolor="#E6E6FA">
<h1><center><b>IMDB</b></center></h1>
  <style>
  table, th, td
  {
  border:lpx solid black;
  }
  </style>
  <table>
  <caption>LIST OF MOVIES</caption>
  <tr>
    <th>Movie</th>
    <th>Edit</th>
    <th>Delete</th>
  </tr>
  <tr> 
  <% @movies.all.each do |movie| %>
  <td><%= link_to movie.name, movie%></td> <td><%=link_to "Edit", edit_movie_path(movie) %></td> <td><%= link_to "Delete", movie_path(movie), method: :delete%> </td>
  </tr> 
    <% end %> 
  </table>
  <% #link_to "Create A New Movie", new_actor_path %>
  <%= link_to "Add Movie", new_movie_path %> 
  <% #link_to "Edit An Actor", edit_actor_path %>
  <% #link_to "Destroy An Actor", edit_actor_path %>
  <%= link_to "Add Actor", actors_path %>
  <%= link_to "User", users_path %>
</body>
</html>

app/views/movies/new.html.erb
<%= simple_nested_form_for @movie do |f| %>
  <%= f. label :Movie_Name %>
  <%= f.text_field :name %>

<h1>SONGS</h1>
<%= f.simple_fields_for :songs do |song| %>
  <%= song. label :Song_Name %>
  <%= song.text_field :name %>
  <%= song. label :Composer_Name %>
  <%= song.text_field :composer %>
  <%= song.link_to_remove "Delete"%>
<% end %>
<%= f.link_to_add "Add new song",:songs %>

<h1>ACTORS</h1>
<%= f.simple_fields_for :movie_actors do |actor1| %>
  <%= actor1.input :actor_id, collection: @actors %>
  <%= actor1.label :Role %>
  <%= actor1.text_field :role%>
  <%= actor1.link_to_remove "Delete"%>
<% end %>
<%= f.link_to_add "Add new Actor",:movie_actors %>

  <br><%= f.button :submit %></br>
<% end %>

app/views/movies/show.html.erb
<%= simple_nested_form_for @movie do |f| %>
  <%= f.label :Movie %>

<h1>SONGS</h1>
<%= f.simple_fields_for :ratings do |rate| %>
  <%= rate.label :rate %>
  <%= rate.input :ratable_id, collection: @movie.songs.all %>
  <%= rate.input :stars, collection: 1..5 %>
  <%= rate.link_to_remove "Delete" %>
<% end %>
  <%= f.link_to_add "Rate new song",:ratings %>
  
  <br><%= f.button :submit %></br>
<% end %>